compact: true
directory: ["."]
evaluate-variables: true
framework: terraform
quiet: true
skip-check:
  - CKV_TF_1
  - CKV_TF_2
summary-position: top

# TODO: remove soft-fail when checks pass
soft-fail: true
