version: 2.1

deploy-feature-branches: &deploy-fb
  filters:
    branches:
      ignore: [main]

deploy-main: &deploy-main
  filters:
    branches:
      only: [main]

executors:
  default:
    working_directory: "/tmp/terraform"
    resource_class: small
    docker:
      - image: hashicorp/terraform:1.5.5

commands:
  install_terragrunt:
    description: Install Terragrunt
    steps:
      - run:
          name: Download Terragrunt
          command: wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.44.4/terragrunt_linux_amd64 -O /usr/local/bin/terragrunt
      - run:
          name: Make Terragrunt executable
          command: chmod u+x /usr/local/bin/terragrunt

jobs:
  terraform_fmt_validate:
    executor: default
    parameters:
      environment:
        type: string
    steps:
      - checkout
      - install_terragrunt
      - run: terraform fmt
      - run: terragrunt hclfmt
      - run: terragrunt run-all validate --terragrunt-non-interactive

  terragrunt_plan:
    executor: default
    parameters:
      environment:
        type: string
    steps:
      - checkout
      - install_terragrunt
      - run:
          name: Terraform Plan
          command: |
            cd environments/<< parameters.environment >>
            terragrunt run-all plan --terragrunt-non-interactive

  terragrunt_apply:
    executor: default
    parameters:
      environment:
        type: string
    steps:
      - checkout
      - install_terragrunt
      - run:
          name: Terraform apply base
          command: |
            cd environments/<< parameters.environment >>/base
            terragrunt run-all apply --terragrunt-non-interactive

      - run:
          name: Terraform apply applications
          command: |
            cd environments/<< parameters.environment >>/applications
            terragrunt run-all apply --terragrunt-non-interactive

      - run:
          name: Terraform apply common
          command: |
            cd environments/<< parameters.environment >>/common
            terragrunt run-all apply --terragrunt-non-interactive

workflows:
  version: 2
  Deploy-to-Development:
    jobs:
      - terraform_fmt_validate:
          name: terraform-fmt-development
          <<: *deploy-fb
          environment: development
          context: trade-tariff-terraform-aws-development

      - terragrunt_plan:
          name: terragrunt-plan-development
          <<: *deploy-fb
          requires:
            - terraform-fmt-development
          environment: development
          context: trade-tariff-terraform-aws-development

      - terragrunt_apply:
          name: terragrunt-apply-development
          <<: *deploy-fb
          requires:
            - terragrunt-plan-development
          environment: development
          context: trade-tariff-terraform-aws-development

      - terragrunt_apply:
          name: terragrunt-apply-development
          <<: *deploy-main
          environment: development
          context: trade-tariff-terraform-aws-development

  Deploy-to-Staging:
    jobs:
      - terraform_fmt_validate:
          name: terraform-fmt-staging
          <<: *deploy-main
          environment: staging
          context: trade-tariff-terraform-aws-staging

      - terragrunt_plan:
          name: terragrunt-plan-staging
          <<: *deploy-main
          requires:
            - terraform-fmt-staging
          environment: staging
          context: trade-tariff-terraform-aws-staging

      - terragrunt_apply:
          name: terragrunt-apply-staging
          <<: *deploy-main
          requires:
            - terragrunt-plan-staging
          environment: staging
          context: trade-tariff-terraform-aws-staging

  Deploy-to-Production:
    jobs:
      - terraform_fmt_validate:
          name: terraform-fmt-production
          <<: *deploy-main
          environment: production
          context: trade-tariff-terraform-aws-production

      - terragrunt_plan:
          name: terragrunt-plan-production
          <<: *deploy-main
          requires:
            - terraform-fmt-production
          environment: production
          context: trade-tariff-terraform-aws-production

      - terragrunt_apply:
          name: terragrunt-apply-production
          <<: *deploy-main
          requires:
            - terragrunt-plan-production
          environment: production
          context: trade-tariff-terraform-aws-production
