# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "terraform-state-development-844815912454"
    encrypt = true
    key     = "./terraform.tfstate"
    region  = "eu-west-2"
  }
}
