name: Deploy to Staging

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: eu-west-2
  PYTHON_VERSION: 3
  TERRAFORM_VERSION: 1.11.0
  TERRAGRUNT_VERSION: 0.78.1

jobs:
  apply-staging:
    environment: staging
    env:
      TF_VAR_backups_basic_auth: ${{ secrets.BACKUPS_BASIC_AUTH }}
      TF_VAR_circleci_organisation_id: ${{ secrets.CIRCLECI_ORGANISATION_ID }}
      TF_VAR_commodi_tea_cookie_signing_secret: ${{ secrets.COMMODI_TEA_COOKIE_SIGNING_SECRET }}
      TF_VAR_commodi_tea_fpo_search_api_key: ${{ secrets.COMMODI_TEA_FPO_SEARCH_API_KEY }}
      TF_VAR_fpo_search_sentry_dsn: ${{ secrets.FPO_SEARCH_SENTRY_DSN }}
      TF_VAR_slack_notify_lambda_slack_webhook_url: ${{ secrets.SLACK_NOTIFY_LAMBDA_SLACK_WEBHOOK_URL }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::451934005581:role/GithubActions-Terraform-Role
          aws-region: ${{ env.AWS_REGION }}

      - uses: trade-tariff/trade-tariff-tools/.github/actions/setup-ssh@main
        with:
          ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}

      - uses: autero1/action-terragrunt@v3
        with:
          terragrunt-version: ${{ env.TERRAGRUNT_VERSION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - run: terragrunt init --all
        working-directory: environments/staging

      - run: terragrunt apply --all
        name: apply-all-base
        working-directory: environments/staging/base

      - run: terragrunt apply --all
        name: apply-all-applications
        working-directory: environments/staging/applications

      - run: terragrunt apply --all
        name: apply-all-common
        working-directory: environments/staging/common

  post-apply-staging:
    needs: apply-staging
    uses: trade-tariff/trade-tariff-tools/.github/workflows/e2e-tests.yml@main
    with:
      test-url: "https://staging.trade-tariff.service.gov.uk"
      admin-test-url: "https://admin.staging.trade-tariff.service.gov.uk"
    secrets:
      basic_password: ${{ secrets.BASIC_PASSWORD }}

  notifications:
      runs-on: ubuntu-latest
      needs: post-apply-staging
      if: always()
      steps:
        - uses: actions/checkout@v4
        - uses: trade-tariff/trade-tariff-tools/.github/actions/slack-notify@main
          with:
            result: ${{ needs.post-apply-staging.result }}
            slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
        - run: if [[ "${{ needs.post-apply-staging.result }}" != "success" ]]; then exit 1; fi
